// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using payment_handler;

namespace payment_handler.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("payment_handler.Models.orderModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("created_at")
                        .HasColumnType("double precision");

                    b.Property<double>("updated_at")
                        .HasColumnType("double precision");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("payment_handler.Models.order_detailsModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("count")
                        .HasColumnType("integer");

                    b.Property<double>("created_at")
                        .HasColumnType("double precision");

                    b.Property<int>("order_id")
                        .HasColumnType("integer");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<double>("updated_at")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("Order_Details");
                });

            modelBuilder.Entity("payment_handler.Models.paymentModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("bank")
                        .HasColumnType("text");

                    b.Property<double>("created_at")
                        .HasColumnType("double precision");

                    b.Property<string>("gross_amount")
                        .HasColumnType("text");

                    b.Property<int>("order_id")
                        .HasColumnType("integer");

                    b.Property<string>("payment_type")
                        .HasColumnType("text");

                    b.Property<int>("transaction_id")
                        .HasColumnType("integer");

                    b.Property<string>("transaction_status")
                        .HasColumnType("text");

                    b.Property<string>("transaction_time")
                        .HasColumnType("text");

                    b.Property<double>("updated_at")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("payment_handler.Models.productModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("created_at")
                        .HasColumnType("double precision");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("price")
                        .HasColumnType("text");

                    b.Property<double>("updated_at")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("payment_handler.Models.user_model", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
